#!/usr/local/bin/python3.6

import boto3
import sys
import urllib.request
import shutil
from zipfile import ZipFile
from os import listdir
from os.path import join

def create_style_css_file():
## Create style.css file
	file = open('./style.css','w')
	file.write('/*=======================================================================================\n')
	file.write('                                         	DEFAULT VALUES                                 \n')
	file.write('\n\n')
	file.write('                                       Font Family       :Roboto Condensed             \n\n')
	file.write('                                       Greenish Blue     :#34c6d3 (Buttons, Icons, Links, Lines & Backgrounds              \n')
	file.write('                                       Steel Gray        :#41464b (Headings)             \n')
	file.write('                                       Blue Bayoux       :#64707b (Paragraphs)           \n')
	file.write('                                       White             :#fff (Text with Black Backgrounds \n')
	file.write('                                       Black             :#000                           \n')
	file.write('\n\n\n')
	file.write('=======================================================================================*/\n')
	file.write('/* General CSS */\n\n')
	file.write('html, body {\n')
	file.write('	height: 100%;\n')
	file.write('}\n\n')	
	file.write('body {\n')
	file.write('	font-family: "Roboto Condensed", sans-serif;\n\n')
	file.write('}\n')
	file.write('p {\n')
	file.write('	color: #64707b;\n')
	file.write('	font-size: 16px;\n')
	file.write('	font-weight: 300;\n')
	file.write('}\n')
	file.write('h3 {\n')
	file.write('	color: #41464b;\n')
	file.write('	text-transform: uppercase;\n')
	file.write('}\n')
	file.write('/*==============================================================\n')
	file.write('				HOME				    \n')
	file.write('==============================================================*/\n')
	file.write('#home {\n')
	file.write('	height: 100%;\n')
	file.write('}\n\n')
	file.write('#home-cover {\n')
	file.write('	height: 100%;\n')
	file.write('	background-image: url("../img/bg-home.jpg");\n')
	file.write('}\n')
	file.write('#home-content-box {\n')
	file.write('	width: 100%;\n')
	file.write('	height: 100%;\n')
	file.write('	display:table;\n')
	file.write('}\n')
	file.write('#home-content-box-inner {\n')
	file.write('	display: table-cell;\n')
	file.write('	vertical-align: middle;\n')
	file.write('}\n')
	file.write('#home-heading h3 {\n')
	file.write('	color: #fff;\n')
	file.write('	font-size: 55px;\n')
	file.write('	font-weight: 700;\n')
	file.write('	margin: 20px 0 20px 0;\n')
	file.write('}\n')
	file.write('/*==============================================================\n')
	file.write('				PARALLAX (Generic)		    \n')
	file.write('==============================================================*/\n')
	file.write('.bg-parallax {\n')
	file.write('	background-repeat: no-repeat;\n')
	file.write('	background-size: cover;\n')
	file.write('	background-position: center;\n')
	file.write('	background-attachment: fixed;\n') ##This is to provide parallax affect
	file.write('}\n')
	file.write('/*==============================================================\n')
	file.write('				BUTTONS (Generic)		    \n')
	file.write('==============================================================*/\n')
	file.write('.btn-general {\n')
	file.write('	border-width: 2px;\n')
	file.write('	border-radius: 0;\n')
	file.write('	padding: 12px 26px 12px 26px;\n')
	file.write('	font-size: 16px;\n')
	file.write('	font-weight: 400;\n')
	file.write('	text-transform: uppercase;\n')
	file.write('}\n')
	file.write('.btn-white {\n')
	file.write('	border-color: #fff;\n')
	file.write('	color: #fff;\n')
	file.write('}\n')
	file.write('.btn-white:hover, .btn-white:focus {\n')
	file.write('	background-color: #fff;\n')
	file.write('	color: #41464b;\n')
	file.write('}\n')
	file.write('.btn-blue {\n')
	file.write('	border-color: #34c6d3;\n')
	file.write('	color: #34c6d3;\n')
	file.write('}\n')
	file.write('.btn-blue:hover, .btn-blue:focus {\n')
	file.write('	background-color: #34c6d3;\n')
	file.write('	color: #fff;\n')
	file.write('}\n')
	file.write('/*==============================================================\n')
	file.write('				ANIMATE				    \n')
	file.write('==============================================================*/\n')
	file.write('#home-cover, #home-heading, #home-btn {;\n')
	file.write('	animation-duration: .5s;\n')
	file.write('}\n')
	file.write('#home-cover {\n')
	file.write('	animation-delay: .1s;\n')
	file.write('}\n')
	file.write('#home-heading {\n')
	file.write('	animation-delay: .5s;\n')
	file.write('}\n')
	file.write('#home-btn {\n')
	file.write('	animation-delay: 1s;\n')
	file.write('}\n')
	file.write('/*==============================================================\n')
	file.write('				CONTENT (Generic)				    \n')
	file.write('==============================================================*/\n')
	file.write('.content-box {\n')
	file.write('	padding:60px 0 60px 0;\n')
	file.write('}\n')
	file.write('.content-title h3 {\n')
	file.write('	font-size: 30px;\n')
	file.write('	font-weight: 700;\n')
	file.write('	text-align: center;\n')
	file.write('	margin: 0 0 30px 0;\n')
	file.write('	font-size: 30px;\n')
	file.write('}\n')
	file.write('.content-title-underline {\n')
	file.write('	width: 30px;\n')
	file.write('	height: 3px;\n')
	file.write('	background-color: #34c6d3;\n')
	file.write('	margin: 0 auto 30px auto;\n')
	file.write('}\n')
	file.write('/*==============================================================\n')
	file.write('				SERVICES				    \n')
	file.write('==============================================================*/\n')
	file.write('.service-item {\n')
	file.write('	padding:20px 0 20px 0;\n')
	file.write('	margin-bottom: 20px;\n')
	file.write('	cursor: pointer;\n')
	file.write('}\n')
	file.write('.service-item-icon i {\n')
	file.write('	color:#34c6d3;\n')
	file.write('	float: left;\n')
	file.write('	padding:15px;\n')
	file.write('	margin-right: 25px;\n')
	file.write('	width: 75px;\n')
	file.write('	height: 75px;\n')
	file.write('	text-align: center;\n')
	file.write('}\n')
	file.write('.service-item:hover .service-item-icon i {\n')
	file.write('	color: #fff;\n')
	file.write('	background-color: #34c6d3 ;\n')
	file.write('}\n')
	file.write('.service-item-title h3 {\n')
	file.write('	font-size: 20px;\n')
	file.write('	font-weight: 400;\n')
	file.write('	margin: 0 0 10px 0;\n')
	file.write('}\n')
	file.write('.service-item-desc p {\n')
	file.write('	margin: 0;\n')
	file.write('	padding-left: 85px ;\n')
	file.write('}\n')


	file.write('/*==============================================================\n')
	file.write('				ABOUT				    \n')
	file.write('==============================================================*/\n')
	file.write('#about-bg-diagonal {\n')
	file.write('	width: 60%;\n')
	file.write('	height: 700px;\n')
	file.write('	float: right; \n')
	file.write('	background-image: url(../img/bg-about.jpg);\n')
	file.write('	border-left: 200px solid #fff;\n')
	file.write('	border-top: 700px solid transparent;\n')
	file.write('}\n')
	file.write('#about-content-box {\n')
	file.write('	float: left; \n')
	file.write('	height: 700px;\n')
	file.write('}\n')
	file.write('#about-content-box-outer {\n')
	file.write('	width: 100%;\n')
	file.write('	height: 100%;\n')
	file.write('	display: table;\n')
	file.write('}\n')
	file.write('#about-content-box-inner {\n')
	file.write('	display: table-cell;\n')
	file.write('	vertical-align: middle;\n')
	file.write('}\n')
	file.write('#about .content-title h3 {\n')
	file.write('	text-align: left;\n')
	file.write('}\n')
	file.write('#about .content-title-underline {\n')
	file.write('	margin: 0 0 30px 0;\n')
	file.write('}\n')
	file.write('#about-desc p {\n')
	file.write('	margin-bottom: 30px;\n')
	file.write('}\n')


	file.write('/*==============================================================\n')
	file.write('				WORK				    \n')
	file.write('==============================================================*/\n')
	file.write('.row.no-gutters [class*=col-] {\n') ## Select all the columns for rows which have no-gutters class
	file.write('	padding-left: 0;\n')
	file.write('	padding-right: 0;\n')
	file.write('}\n')
	file.write('.img-wrapper {\n')
	file.write('	overflow: hidden;\n')
	file.write('}\n')
	file.write('.img-wrapper img {\n')
	file.write('	transition: transform;\n')
	file.write('}\n')
	file.write('.img-wrapper img:hover {\n')
	file.write('	transform: scale(1.5);\n')
	file.write('	cursor: zoom-in;\n')
	file.write('}\n')
	file.write('}\n')
	


	file.close()
